### ISSUE TITLE
Please provide changelog

### ISSUE THREAD

**Issue by landau** [keverw/range_check#11]
I've been using this module since `0.0.5` and I haven't updated it since. This module is now at `1.2.0`, but I don't know what breaking change occured.

Thanks.

**Comment by keverw** [comment]
I thought git history counted as a change log. But anyways, there shouldn't of been any breaking changes. Just code cleanup and a new IP to check if an range itself is valid.

Version number I accidently bumped up instead of a dependency, so I just stuck with it. It shouldn't break anything.

**Comment by landau** [comment]
Git history can be useful for seeing changes if the messages are useful. However, the messages found in this repo lack what the version is being changed to and many messages. A changelog should show a overview of important fixes and changes/additions.

https://github.com/request/request/blob/master/CHANGELOG.md has a really nice changelog (not that I'm saying you should go crazy over it), but somewhere where I could see something like:

```
#### 1.2.0
- Fixes XYZ
- Adds ABC
```

Thanks!

**Comment by keverw** [comment]
Thanks for the feedback. Usually change logs aren't my thing but I get your point also. Change log more useful for people who don't want to read the whole git history which could get very long :)

I'll start providing one for future changes.
