### ISSUE TITLE
Numbers up to 10 digits are valid IPs?

### ISSUE THREAD

**Issue by AlSherif** [keverw/range_check#14]
Is this intended? 
rangeCheck.isIP('0123456789')  will return true.
Is there a specification by which this is a valid IP?

**Comment by keverw** [comment]
Hi, that doesn't sound like a valid one to me. That function wraps around https://www.npmjs.com/package/ipaddr.js

https://runkit.com/58a5b81f2448b700144a58f7/58a5b81f2448b700144a58f8 when I check that one, it's also reporting true. I wonder if @whitequark might know.

**Comment by whitequark** [comment]
https://github.com/whitequark/ipaddr.js/issues/44

**Comment by whitequark** [comment]
@AlSherif to answer your question: yes there is, the inet_aton function accepts it, and your system `ping` program does also. Try it.

**Comment by AlSherif** [comment]
Yeah thanks, it seems like you can pass IP addresses in a decimal integer format as well, which is just the decimal conversion of the complete binary IP address.

I get different IP addresses though for rangeCheck.isIP('0123456789') and rangeCheck.isIP('123456789'), which seems weird.

**Comment by AlSherif** [comment]
By the way.. how do I specify and IP range that matches all ipv4 and/or all ipv6 addresses?

**Comment by AlSherif** [comment]
0.0.0.0/0 and ::/0.
Thanks :)

**Comment by whitequark** [comment]
> I get different IP addresses though for ipaddr.parse('0123456789')

This one is octal.
