### ISSUE TITLE
version() and isIP() returning unexpected results.

### ISSUE THREAD

**Issue by STLMikey** [keverw/range_check#25]
Forgot to sanitize an input, and ended up passing the string "1" to version() and isIP().

version("1"); // returns 4
isIP("1"); // returns true

**Comment by amirbardugo** [comment]
@STLMikey the issue is in ipaddr.js apparently https://github.com/whitequark/ipaddr.js/issues/44
they have another function that ignore it @keverw anyway to switch to this one? 
`ipaddr.IPv4.isValidFourPartDecimal`

**Comment by keverw** [comment]
I decided to upgrade the build scripts, and did this as one of the first fixes. Will be in the future 3.0 release!
